# Generated by Django 6.0.7 on 2026-07-27 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='bots.telegrambot')),
            ],
        ),
        migrations.CreateModel(
            name='CommandResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='bots.botcommand')),
            ],
        ),
        migrations.AddConstraint(
            model_name='botcommand',
            constraint=models.UniqueConstraint(fields=('bot', 'name'), name='unique_command_per_bot'),
        ),
    ]
