# Generated by Django 6.0.7 on 2026-07-27 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_botcommand_commandresponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandresponse',
            name='command',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='bots.botcommand'),
        ),
    ]
