# Generated by Django 6.0.7 on 2026-07-28 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_alter_commandresponse_command'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrambot',
            old_name='is_active',
            new_name='needs_sync',
        ),
    ]
