# Generated by Django 6.0.7 on 2026-07-28 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_rename_is_active_telegrambot_needs_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandresponse',
            name='command',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='bots.botcommand'),
        ),
    ]
