# Generated by Django 6.0.7 on 2026-08-01 00:05

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_alter_commandresponse_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='webhook_secret',
            field=models.CharField(default=secrets.token_hex, max_length=64, unique=True),
        ),
    ]
